Update
macs1207/HowFun-blessing-generator pull request #8
Opened 2020-06-04 03:47 UTC by daidaidarwa

2020-06-04 04:24 UTC, daidaidarwa commented
add feedback file

2020-06-04 09:28 UTC, Catossun requested changes
Hi @daidaidarwa 
給你一點小建議

2020-06-04 09:28 UTC, Catossun commented on server.py
> +    if request.method == 'POST':
Hi @daidaidarwa 
`method`已經指定為`POST`就可以不用再檢查一次了

2020-06-04 09:28 UTC, Catossun commented on server.py
> +        text = request.values.get('feedback')
建議加個判斷`text`是否為`None` ，如果是的話應該要回應 Bad Request (400)

2020-06-04 09:28 UTC, Catossun commented on server.py
> +            return make_response("too long", 500)
這方面算是請求格式錯誤，應該要回應 Bad Request (400)

2020-06-04 09:34 UTC, Catossun requested changes

2020-06-04 09:34 UTC, Catossun commented on server.py
> +        text = request.values.get('feedback')
建議加個判斷`text`是否為`None` ，如果是的話應該要回應 Bad Request (400)
```suggestion
        text = request.values.get('feedback')
        if text is not None:
            # Some code here
        else:
            return make_response("need feedback", 400)
```

2020-06-04 10:01 UTC, macs1207 commented on server.py
> +    if request.method == 'POST':
這個應該是被我影響的XD

2020-06-04 10:28 UTC, daidaidarwa commented
感謝你的建議，狀態碼的部分因為我第一次寫api不太了解所以就參照之前的方法了
判斷text方法我有更新上去了

2020-06-04 12:26 UTC, Catossun requested changes
怪怪的🤔

2020-06-04 12:26 UTC, Catossun commented on server.py
> +        return make_response("feedback empty", 400)
`text`如果是`None`的話，呼叫`strip()`應該會報錯吧？
> 由於客戶端未傳送`feedback`參數，故`values.get(str)`預設回傳None，詳閱：[Class MultiDict.get(str)](https://werkzeug.palletsprojects.com/en/1.0.x/datastructures/#werkzeug.datastructures.MultiDict.get)。

應該要先判斷是否不為`None`，再對`text`做其他處理，才不會有伺服端錯誤(Http Status Code 500)。
```suggestion
    text = request.values.get('feedback')
    if text is not None:
        # Use text here
    else:
        return make_response("need feedback", 400)
```

2020-06-04 12:32 UTC, macs1207 commented on server.py
> +@app.route('/api/feedback', method = ['POST'])
@daidaidarwa  這個你有跑過ㄇ 這樣應該跑不起來
```python
@app.route('/api/feedback', method = ['POST'])
```
改成這樣
```python
@app.route('/api/feedback', methods=['POST'])
```

2020-06-04 12:32 UTC, macs1207 commented on server.py
> +@app.route('/api/feedback', method = ['POST'])
其他的我晚點再看

2020-06-04 12:59 UTC, daidaidarwa commented on server.py
> +@app.route('/api/feedback', method = ['POST'])
要加S阿...

2020-06-04 13:03 UTC, macs1207 commented on server.py
> +@app.route('/api/feedback', method = ['POST'])
你可能還是跑起來打 API 確認一下

2020-06-04 13:04 UTC, daidaidarwa commented on server.py
> +        return make_response("feedback empty", 400)
我的想法是讓他不要送空白的字串才這樣設計的如果  text = "" 用 if text is none就不會被擋下 來了 
```suggestion
    text = request.values.get('feedback')
    if not text.strip():
        return make_response("feedback empty", 400)
```

2020-06-04 13:07 UTC, daidaidarwa commented on server.py
> +@app.route('/api/feedback', method = ['POST'])
好

2020-06-04 14:12 UTC, daidaidarwa commented on server.py
> +        return make_response("feedback empty", 400)
我了解你的意思了剛剛有再去檢查過

2020-06-04 14:28 UTC, daidaidarwa commented
`text = request.get_data()
    text = json.loads(text)
    text = text.get('feedback')
    if text is None:
        return make_response("need feedback", 400)`
這裡我用 value.get 或是 form-data 都拿不到 用這個就拿到了 我也有多加一層判斷text是否為None了

2020-06-04 15:21 UTC, Catossun commented on server.py
> +        return make_response("feedback empty", 400)
👍

2020-06-04 15:45 UTC, daidaidarwa commented
已修正完成

2020-06-05 15:45 UTC, macs1207 approved these changes
下次要發的時候
commit message 還是寫一下比較好

2020-06-05 16:00 UTC, merged